name: eric
channels:
  - pytorch-lts
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - conda-forge::cudatoolkit-dev=11.4.0
  - numpy=1.21.2
  - pandas=1.3.5
  - pathlib=1.0.1
  - python=3.7.11
  - pytorch-lts::pytorch=1.8.2
  - regex=2022.1.18
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - tensorboard=2.6.0
